var g_levels_data=[[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,2,2,2,2,2,2,0,0,0,0,0,0,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,0,3,3,3,0,3,3,3,0,0,0,0,0,0,2,2,2,2,2,2,2,0,0,0,0,0,0,1,1,1,3,1,1,1,0,0,0,0,0,0,0,0,6,
6,6,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,6,0,0,0,0,0,0,0,0,0,0,0,6,4,6,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,0,0,0,0,1,3,3,3,3,3,3,3,1,0,0,0,0,1,3,0,3,3,3,0,3,1,0,0,0,0,1,3,0,3,3,3,0,3,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,6,0,6,0,0,0,0,0,0,6,1,1,1,1,1,1,1,1,1,6,0,0,6,1,1,1,1,5,1,1,1,1,6,0,0,6,2,2,2,5,5,5,2,2,2,6,0,0,6,2,6,5,5,5,5,5,6,2,6,0,0,6,3,3,6,5,5,5,6,3,3,6,0,0,6,3,3,3,5,5,5,3,3,3,6,0,0,6,6,4,4,6,5,6,4,4,6,6,0,0,0,6,6,4,4,4,4,4,6,6,0,0,0,0,0,6,6,6,6,6,6,6,0,0,0,0,0,0,0,6,6,6,6,6,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,6,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,2,3,0,0,0,0,0,0,0,3,2,1,1,2,3,0,0,6,0,6,0,0,3,2,1,1,2,3,4,5,6,0,6,5,4,3,2,1,1,2,3,4,5,6,0,6,5,4,3,2,1,6,6,6,6,6,6,0,6,6,6,6,6,6,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,3,3,3,0,0,0,0,0,0,
0,0,0,0,3,5,3,0,0,0,0,0,0,0,0,0,0,3,5,3,0,0,0,0,0,0,2,2,2,0,3,5,3,0,2,2,2,0,0,2,4,2,0,3,5,3,0,2,4,2,0,0,2,2,2,0,3,3,3,0,2,2,2,0,0,0,0,0,0,6,6,6,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,2,2,2,2,2,2,0,0,0,0,3,3,3,3,3,3,3,3,3,3,3,0,3,3,4,3,3,3,4,3,3,3,4,3,3,0,0,0,0,0,0,0,0,0,0,0,0,0,6,6,3,6,6,6,3,6,6,6,3,6,6,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]],g_levels_backgrounds=[0,0,1,1,2,2,3,3],g_block_values=[0,10,20,30,40,50,80],g_block_normals=[{x:-1,y:0},{x:0,y:1},{x:1,y:0},{x:0,y:-1}],g_block_powerup_probs=
[{prob:0,allowed_powerups:[],allowed_powerups_prob:[]},{prob:.2,allowed_powerups:[0],allowed_powerups_prob:[1]},{prob:.25,allowed_powerups:[0],allowed_powerups_prob:[1]},{prob:.2,allowed_powerups:[0,1],allowed_powerups_prob:[.5,1]},{prob:.25,allowed_powerups:[0,1],allowed_powerups_prob:[.3,1]},{prob:.3,allowed_powerups:[0,1,2],allowed_powerups_prob:[.4,.6,1]},{prob:0,allowed_powerups:[],allowed_powerups_prob:[]}],g_powerup_value=[50,50,50],g_powerup_duration=[25,10,15];
function new_vector(a,b){return{x:a,y:b}}function mul(a,b){return{x:a.x*b.x,y:a.y*b.y}}function smul(a,b){return{x:a*b.x,y:a*b.y}}function sub(a,b){return{x:a.x-b.x,y:a.y-b.y}}function add(a,b){return{x:a.x+b.x,y:a.y+b.y}}function dot(a,b){return a.x*b.x+a.y*b.y}function magnitude(a){return Math.sqrt(a.x*a.x+a.y*a.y)}function noz(a){var b={x:0,y:0},c=a.x*a.x+a.y*a.y;0<c&&(c=Math.sqrt(c),b.x=a.x/c,b.y=a.y/c);return b}function approx_equal(a,b,c){void 0===c&&(c=.01);return Math.abs(a-b)<c}
function calculate_line_intersection(a,b,c,d){var e=new_vector(0,0);b=sub(b,a);d=sub(c,d);var f=sub(a,c);c=b.y*d.x-b.x*d.y;var g=d.y*f.x-d.x*f.y;d=!0;if(0<c){if(0>g||g>c)d=!1}else if(0<g||g<c)d=!1;if(d)if(f=b.x*f.y-b.y*f.x,0<c){if(0>f||f>c)d=!1}else if(0<f||f<c)d=!1;d&&!approx_equal(c,0,.01)&&(c=g/c,0<=c&&1>=c?e=add(a,smul(c,b)):d=!1);return{exists:d,P:e}}
function compute_rect_info(a,b){var c=2*b,d=a.x+c;a=a.y+c;b=new_vector(-b,-b);c=add(b,new_vector(0,a));d=add(c,new_vector(d,0));a=sub(d,new_vector(0,a));return{Po:{x:0,y:0},lines:[[b,c],[c,d],[d,a],[a,b]]}}
function check_moving_circle_vs_static_rect(a,b,c){var d={};a=sub(a,c.Po);b=sub(b,c.Po);for(var e=9999999999999,f=0,g=0;4>g;++g){var h=c.lines[g];h=calculate_line_intersection(b,a,h[0],h[1]);if(h.exists){var l=magnitude(sub(h.P,b));l<e&&(e=l,d.I=noz(sub(b,h.P)),d.N=g_block_normals[g],f=dot(d.I,d.N),d.interpenetration=magnitude(sub(a,h.P))+1)}}9999999999999>e&&(d.occurred=!0,a=smul(f,d.N),d.R=sub(smul(2,a),d.I));return d}var SpriteID;
(function(a){a[a.Ball=0]="Ball";a[a.Ball_Op=1]="Ball_Op";a[a.Paddle=2]="Paddle";a[a.Paddle_w_lasers=3]="Paddle_w_lasers";a[a.Block_1=4]="Block_1";a[a.Block_2=5]="Block_2";a[a.Block_3=6]="Block_3";a[a.Block_4=7]="Block_4";a[a.Block_5=8]="Block_5";a[a.Block_6=9]="Block_6";a[a.Powerup_1=10]="Powerup_1";a[a.Powerup_2=11]="Powerup_2";a[a.Powerup_3=12]="Powerup_3";a[a.Powerup_4=13]="Powerup_4";a[a.Powerup_5=14]="Powerup_5";a[a.Laser_Beam=15]="Laser_Beam"})(SpriteID||(SpriteID={}));
var Renderer=function(){function a(){var b=this;this.canvas_size=new_vector(0,0);this.background_patterns=[];this.images=[];var a=document.getElementById("canvas");if(null==a)throw Error("Canvas is null!");var d=a.getContext("2d");if(null==d)throw Error("Canvas context is null!");d.lineCap="round";d.lineJoin="round";d.strokeStyle="black";d.lineWidth=1;for(var e=["data\\bitmaps\\background_1.png","data\\bitmaps\\background_2.png","data\\bitmaps\\background_3.png","data\\bitmaps\\background_4.png"],
f=function(a){var c=new Image;c.src=e[a];c.onload=function(){var d=b.canvas_ctx.createPattern(c,"repeat");d&&(b.background_patterns[a]=d)}},g=0;g<e.length;++g)f(g);f="data\\bitmaps\\ball.png data\\bitmaps\\ball_op.png data\\bitmaps\\paddle.png data\\bitmaps\\paddle_w_lasers.png data\\bitmaps\\block_1.png data\\bitmaps\\block_2.png data\\bitmaps\\block_3.png data\\bitmaps\\block_4.png data\\bitmaps\\block_5.png data\\bitmaps\\block_6.png data\\bitmaps\\powerup_1.png data\\bitmaps\\powerup_2.png data\\bitmaps\\powerup_3.png data\\bitmaps\\powerup_4.png data\\bitmaps\\powerup_5.png data\\bitmaps\\powerup_4.png".split(" ");
for(g=0;g<f.length;++g){var h=new Image;h.src=f[g];this.images[g]=h}this.canvas=a;this.canvas_ctx=d;this.resize()}a.prototype.resize=function(){var b=this.canvas;b.width=window.innerWidth;b.height=window.innerHeight;this.canvas_size=new_vector(this.canvas.width,this.canvas.height)};a.prototype.clear_canvas=function(){this.canvas_ctx.clearRect(0,0,this.canvas.width,this.canvas.height)};a.prototype.draw_background=function(b){void 0===b&&(b=0);b=b<this.background_patterns.length?b:0;if(b=this.background_patterns[b]){var a=
this.canvas_ctx;a.beginPath();a.fillStyle=b;a.fillRect(0,0,this.canvas.width,this.canvas.height)}};a.prototype.draw_line=function(b,a,d){var c=this.canvas_ctx;c.beginPath();c.strokeStyle=d;c.moveTo(b.x,b.y);c.lineTo(a.x,a.y);c.stroke()};a.prototype.draw_image=function(b,a,d){this.canvas_ctx.drawImage(this.images[b],a.x,a.y,d.x,d.y)};a.prototype.draw_text=function(b,a,d){this.canvas_ctx.font=a+"px Verdana";this.canvas_ctx.textAlign="center";this.canvas_ctx.fillText(d,b.x,b.y)};return a}(),SoundID;
(function(a){a[a.Paddle_1=0]="Paddle_1";a[a.Paddle_2=1]="Paddle_2";a[a.Paddle_3=2]="Paddle_3";a[a.Block=3]="Block";a[a.Block_5=4]="Block_5";a[a.Laser=5]="Laser";a[a.Lost_Ball=6]="Lost_Ball";a[a.Powerup_1=7]="Powerup_1";a[a.Powerup_2=8]="Powerup_2";a[a.Powerup_3=9]="Powerup_3";a[a.Powerup_4=10]="Powerup_4"})(SoundID||(SoundID={}));
var Sound=function(){function a(){this.data=[];for(var b="data\\audio\\paddle_1.wav data\\audio\\paddle_2.wav data\\audio\\paddle_3.wav data\\audio\\block.wav data\\audio\\block_5.wav data\\audio\\laser.wav data\\audio\\lost_ball.wav data\\audio\\powerup_1.wav data\\audio\\powerup_2.wav data\\audio\\powerup_3.wav data\\audio\\powerup_4.wav".split(" "),a=0;a<b.length;++a){var d=new Audio(b[a]);this.data.push(d)}}a.prototype.play=function(b){};return a}(),Ball=function(){function a(b,a){this.radius=
1;this.size=new_vector(0,0);this.half_size=new_vector(0,0);this.start_speed=.35;this.max_speed=2;this.speed_increase_factor=1.025;this.P=new_vector(0,0);this.oldP=new_vector(0,0);this.dP=new_vector(0,0);this.dp_scale=1;this.is_op_remaining_time=0;this.renderer=b;this.sound=a;this.dp_scale=b.canvas.height}a.prototype.resize=function(b){this.radius=.3*b.y;this.size=new_vector(2*this.radius,2*this.radius);this.half_size=smul(.5,this.size);this.dp_scale=this.renderer.canvas.height};a.prototype.reset=
function(){this.oldP=this.P=new_vector(0,0);this.dP=new_vector(0,0);this.is_op_remaining_time=0};a.prototype.collided_with_wall=function(){var b=this.P,a=this.radius,d=this.renderer.canvas.width,e=b.x+a>=d,f=0>=b.y-a;0>=b.x-a?(this.P.x=this.radius+1,this.oldP=this.P,this.dP.x*=-1):e?(this.P.x=d-this.radius-1,this.oldP=this.P,this.dP.x*=-1):f&&(this.P.y=this.radius+1,this.dP.y*=-1)};a.prototype.update=function(a){this.oldP=this.P;if(magnitude(this.dP)>this.max_speed){var b=noz(this.dP);this.dP=smul(this.max_speed,
b)}this.P=add(this.P,smul(a,smul(this.dp_scale,this.dP)));0<this.is_op_remaining_time&&(this.is_op_remaining_time-=a)};a.prototype.render=function(){this.renderer.draw_image(SpriteID.Ball+(0<this.is_op_remaining_time?1:0),sub(this.P,this.half_size),this.size)};return a}(),Player=function(){function a(a,c){this.P=new_vector(0,0);this.move_target_x=0;this.original_size=new_vector(10,10);this.current_size=new_vector(10,10);this.lives=3;this.lasers_remaining_time=this.wide_remaining_time=this.score=0;
this.laser_beams=[];this.renderer=a;this.sound=c;this.P=new_vector(.5*a.canvas.width,.5*a.canvas.height);this.move_target_x=this.P.x;this.laser_beam_size=new_vector(10,10)}a.prototype.resize=function(a){this.original_size=mul(new_vector(1.2,.6),a);this.current_size=mul(new_vector(0<this.wide_remaining_time?2:1,1),this.original_size);a=.7*a.y;this.laser_beam_size=new_vector(.5*a,a)};a.prototype.reset=function(){this.remove_wide();this.remove_lasers()};a.prototype.place_ball_on_paddle=function(a){var b=
this.P,d=smul(.5,this.current_size);a.P=new_vector(b.x,b.y-d.y-a.radius-1);a.dP=new_vector(0,0);a.oldP=a.P};a.prototype.serve_ball=function(a){var b=noz(new_vector(-.0025*(this.P.x-this.move_target_x),-1));a.dP=smul(a.start_speed,b)};a.prototype.make_wide=function(){this.wide_remaining_time=g_powerup_duration[Powerup_Type.Wide_Paddle];var a=this.original_size;this.current_size=new_vector(2*a.x,a.y)};a.prototype.remove_wide=function(){this.wide_remaining_time=0;this.current_size=this.original_size};
a.prototype.add_lasers=function(){this.lasers_remaining_time=10};a.prototype.remove_lasers=function(){this.lasers_remaining_time=0;this.laser_beams=[]};a.prototype.fire_lasers=function(){if(0<this.lasers_remaining_time){var a=this.laser_beam_size;a=new_vector(this.P.x-.5*a.x,this.P.y-(.5*this.current_size.y+a.y));this.laser_beams.push(a)}};a.prototype.update=function(a){var b=.5*this.current_size.x;this.P.x+=.1*(this.move_target_x-this.P.x);this.P.x=Math.max(b,Math.min(this.renderer.canvas.width-
b,this.P.x));0<this.wide_remaining_time&&(this.wide_remaining_time-=a,0>=this.wide_remaining_time&&this.remove_wide());0<this.lasers_remaining_time&&(this.lasers_remaining_time-=a,0>=this.lasers_remaining_time&&this.remove_lasers());b=this.laser_beams;for(var d,e=0;e<b.length;++e)d=b[e],d.y-=500*a,0>=d.y+this.laser_beam_size.y&&b.splice(e,1)};a.prototype.render=function(){var a=this.renderer,c=this.current_size,d=smul(.5,c);a.draw_image(SpriteID.Paddle+(0<this.lasers_remaining_time?1:0),sub(this.P,
d),c);for(var e=0,f=this.laser_beams;e<f.length;e++){d=f[e];var g=this.laser_beam_size,h=new_vector(.5*g.x,0);d=sub(d,h);this.renderer.draw_image(SpriteID.Laser_Beam,d,g)}e=a.canvas.height-c.y;f=.4*c.x;if(0<this.lives-1)for(d=new_vector(15,e),c=smul(.25,c),g=0;g<this.lives-1;++g)a.draw_image(SpriteID.Paddle,d,c),d.x+=f;a.canvas_ctx.font="14px Verdana";a.canvas_ctx.fillStyle="white";a.canvas_ctx.textAlign="right";a.canvas_ctx.textBaseline="middle";a.canvas_ctx.fillText("Score: "+this.score,this.renderer.canvas.width-
15,e)};return a}(),Powerup_Type;(function(a){a[a.Wide_Paddle=0]="Wide_Paddle";a[a.Lasers=1]="Lasers";a[a.Ball_Is_Op=2]="Ball_Is_Op"})(Powerup_Type||(Powerup_Type={}));
var Game_Objects=function(){function a(a,c){this.screen_offset=new_vector(0,0);this.block_data=[];this.block_size=new_vector(0,0);this.column_count=13;this.row_count=15;this.blocks_remaining=0;this.dropping_powerups=[];this.powerup_size=new_vector(0,0);this.renderer=a;this.sound=c;this.resize()}a.prototype.resize=function(){var a=this.renderer.canvas.height,c=this.renderer.canvas.width/this.column_count,d=Math.floor(c/2);(this.row_count+5)*d>a&&(d=Math.floor(a/(this.row_count+5)));this.block_size=
new_vector(c,d);this.powerup_size=new_vector(.5*this.block_size.x,.5*this.block_size.x);this.screen_offset=new_vector(0,3*this.block_size.y)};a.prototype.reset=function(){this.dropping_powerups=[]};a.prototype.init_level=function(a){this.reset();this.blocks_remaining=0;this.block_data=[];for(var b=this.row_count*this.column_count,d=a.length,e=0;e<b;++e)if(e<d){var f=a[e];6==f&&(f=8);this.block_data.push(f);0<f&&++this.blocks_remaining}else this.block_data.push(0),console.log("Error: index ("+e+") was larger than level_data ("+
a.length+").")};a.prototype.add_powerup=function(a,c){if(0<=a&&a<g_block_powerup_probs.length-1){var b=g_block_powerup_probs[a],e=Math.random();if(e<=b.prob){a={};e=Math.random();for(var f=a.type=0;f<b.allowed_powerups.length;++f)if(e<=b.allowed_powerups_prob[f]){a.type=f;break}b=this.powerup_size;e=smul(.5,b);c=sub(c,e);c.x=Math.max(0,Math.min(this.renderer.canvas.width-b.x,c.x));a.P=c;this.dropping_powerups.push(a)}}};a.prototype.update=function(a,c){var b=[],e=this.dropping_powerups,f=smul(.5,
this.powerup_size),g=smul(.5,c.current_size),h=add(g,f);g=sub(c.P,h);h=add(c.P,h);for(var l=new_vector(0,100),k=0;k<e.length;++k){var m=e[k];m.P=add(m.P,smul(a,l));m.remaining_time=10;if(m.P.y>this.renderer.canvas.height)e.splice(k,1);else{var n=add(m.P,f);n.x>=g.x&&n.x<=h.x&&n.y>=g.y&&n.y<=h.y&&(b.push(m),c.score+=g_powerup_value[m.type],e.splice(k,1))}}return b};a.prototype.render=function(){for(var a=this.renderer,c=this.block_size,d=this.column_count,e=this.row_count,f=this.screen_offset,g,h=
0;h<e;++h)for(var l=0;l<d;++l){var k=this.block_data[this.column_count*h+l];0<k&&(--k,k=Math.max(0,Math.min(5,k)),g=new_vector(l,h),g=mul(g,c),g=add(g,f),a.draw_image(SpriteID.Block_1+k,g,c))}a=0;for(c=this.dropping_powerups;a<c.length;a++)d=c[a],this.renderer.draw_image(SpriteID.Powerup_1+d.type,d.P,this.powerup_size)};return a}(),Game_Mode;
(function(a){a[a.Idle=0]="Idle";a[a.Serving=1]="Serving";a[a.Playing=2]="Playing";a[a.Dead=3]="Dead";a[a.Game_Over=4]="Game_Over";a[a.Won_Level=5]="Won_Level";a[a.Won_Game=6]="Won_Game"})(Game_Mode||(Game_Mode={}));
var Game=function(){function a(){var a=this;this.curr_level_index=this.last_update=0;this.curr_mode=Game_Mode.Serving;this.resize=function(){var b=a.ball,c=a.renderer,d=a.game_objects,h=a.player,l=d.block_size,k=h.current_size;c.resize();d.resize();b.resize(l);h.resize(l);d=c.canvas.width;h.P.y=c.canvas.height-4*k.y;b.P.y+b.radius>h.P.y-k.y&&(b.P.y=h.P.y-3*k.y);b.P.x+b.radius>d&&(b.P.x=d-3*b.radius)};this.press_event_handler=function(){var b=a.curr_mode,c=a.player;switch(b){case Game_Mode.Playing:c.fire_lasers();
break;case Game_Mode.Serving:c.serve_ball(a.ball);b=Game_Mode.Playing;break;case Game_Mode.Dead:b=0>=--c.lives?Game_Mode.Game_Over:Game_Mode.Serving;break;case Game_Mode.Game_Over:c.lives=3;c.score=0;a.curr_level_index=0;a.game_objects.init_level(g_levels_data[0]);b=Game_Mode.Serving;break;case Game_Mode.Won_Level:c.reset();a.curr_level_index=(a.curr_level_index+1)%g_levels_data.length;a.game_objects.init_level(g_levels_data[a.curr_level_index]);b=Game_Mode.Serving;break;case Game_Mode.Won_Game:c.reset(),
c.lives=3,a.curr_level_index=0,a.game_objects.init_level(g_levels_data[0]),b=Game_Mode.Serving}a.curr_mode=b};this.move_event_handler=function(b){var c=b.changedTouches?b.changedTouches[0].pageX:b.pageX;c-=a.renderer.canvas.offsetLeft;a.player.move_target_x=c;b.preventDefault()};this.update_and_render=function(b){if(a.is_running){var c=a.renderer,d=a.player,e=a.ball,l=a.game_objects,k=0==a.last_update?1/60:b-a.last_update;b=a.curr_mode;if(b>Game_Mode.Idle)if(d.update(k),b==Game_Mode.Serving)d.place_ball_on_paddle(e);
else if(b==Game_Mode.Playing)if(0<l.blocks_remaining){e.update(k);var m=0;for(k=l.update(k,d);m<k.length;m++)switch(k[m].type){case Powerup_Type.Lasers:d.lasers_remaining_time=g_powerup_duration[Powerup_Type.Lasers];break;case Powerup_Type.Ball_Is_Op:e.is_op_remaining_time=g_powerup_duration[Powerup_Type.Ball_Is_Op];break;case Powerup_Type.Wide_Paddle:d.make_wide()}e.P.y-e.radius>c.canvas.height?(b=Game_Mode.Dead,a.sound.play(SoundID.Lost_Ball),d.reset(),l.reset(),e.reset()):a.handle_collisions()}else b=
Game_Mode.Won_Level;a.curr_mode=b;c.clear_canvas();c.draw_background(g_levels_backgrounds[a.curr_level_index]);l.render();d.render();e.render();b==Game_Mode.Dead?(d=smul(.5,c.canvas_size),c.draw_text(d,30,"Oh noes!"),d.y+=50,c.draw_text(d,20,"You've lost a life")):b==Game_Mode.Game_Over?(d=smul(.5,c.canvas_size),c.draw_text(d,40,"Game Over!"),d.y+=50,c.draw_text(d,20,"You've lost, try again")):b==Game_Mode.Won_Level?(d=smul(.5,c.canvas_size),c.draw_text(d,40,"Victory!"),d.y+=50,c.draw_text(d,20,"Onwards to the next level")):
b==Game_Mode.Won_Game&&(d=smul(.5,c.canvas_size),c.draw_text(d,40,"Congratulations!"),d.y+=50,c.draw_text(d,20,"You have beaten the game"));window.requestAnimationFrame(a.update_and_render)}};var c=this.renderer=new Renderer,d=this.sound=new Sound;this.game_objects=new Game_Objects(c,d);this.game_objects.init_level(g_levels_data[this.curr_level_index]);this.player=new Player(c,d);this.ball=new Ball(c,d);this.resize();this.is_running=!0;c=c.canvas;c.addEventListener("mousedown",this.press_event_handler);
c.addEventListener("touchstart",this.press_event_handler);c.addEventListener("mousemove",this.move_event_handler);c.addEventListener("touchmove",this.move_event_handler);window.addEventListener("resize",this.resize,!1);window.requestAnimationFrame(this.update_and_render)}a.prototype.handle_collisions=function(){for(var a,c=this.ball,d=this.game_objects,e=this.player,f=d.column_count,g=d.row_count,h=d.screen_offset,l=d.block_size,k=d.block_data,m=compute_rect_info(l,c.radius),n,z=0<c.is_op_remaining_time,
r,w=e.laser_beams,p=!1,x=this.game_objects.powerup_size,A=smul(.5,x),t=0;t<g;++t)for(var u=0;u<f;++u){var y=f*t+u,q=k[y];if(0<q){n=new_vector(u,t);n=mul(n,l);n=add(n,h);m.Po=n;a=check_moving_circle_vs_static_rect(c.P,c.oldP,m);if(!a.occurred)for(var v=0;v<w.length;++v)r=w[v],r.x+A.x>=n.x&&r.x-A.x<=n.x+x.x&&r.y<=n.y+x.y&&(p=!0,w.splice(v,1));if(a.occurred||p)7>q||z?(k[y]=0,--d.blocks_remaining,this.sound.play(SoundID.Block)):(k[y]=q-1,this.sound.play(SoundID.Block_5)),0<q&&6>q&&(e.score+=g_block_values[q],
n=add(n,smul(.5,l)),0>=c.is_op_remaining_time&&d.add_powerup(q,n)),z||p||(c.P=add(c.P,smul(a.interpenetration+1,a.I)),p=magnitude(c.dP),c.dP=smul(p,a.R)),p=!1}}d=e.current_size;m=compute_rect_info(d,c.radius);m.Po=sub(e.P,smul(.5,d));a=check_moving_circle_vs_static_rect(c.P,c.oldP,m);a.occurred&&(c.P=add(c.P,smul(a.interpenetration+1,a.N)),m=0<=a.R.y?1:-1,a=noz(new_vector(e.move_target_x-e.P.x,250*m)),e=(c.P.x-(e.P.x-.5*d.x))/d.x,0<=e&&.2>e?(a=noz(new_vector(-2,m)),this.sound.play(SoundID.Paddle_2)):
.8<=e&&1>=e?(a=noz(new_vector(2,m)),this.sound.play(SoundID.Paddle_2)):this.sound.play(SoundID.Paddle_1),p=c.speed_increase_factor*magnitude(c.dP),c.dP=smul(p,noz(a)));c.collided_with_wall()};return a}(),game=new Game;window.requestAnimationFrame(game.update_and_render);
